config/routes.rb
Rails.application.routes.draw do
#ActionController::Routing::Routes.draw do |map|
  root 'query#index#form', :action => "index", :controller => "query"
  #map.root :controller => "query", :controller => "query", :action => "index", :format => 'html'
  get '/query' => 'query#index#form', :format => 'html'
  post '/query' => 'query#index#form', :format => 'html', :action => "index", :controller => "query"
  post '/' => 'query#index#form', :format => 'html', :action => "index", :controller => "query"
  get '/about' => 'query#about', :format => 'html'
  get '/help' => 'query#help', :format => 'html'
  #root 'query#index#form',:format => 'bgps', :action => "index", :controller => "query"
  #map.root :controller => "query", :controller => "query", :action => "index", :format => 'html'
  get '/query' => 'query#index#form', :format => 'bgps'
  post '/query' => 'query#index#form', :format => 'bgps', :action => "index", :controller => "query"
  get '/about' => 'query#about', :format => 'bgps'
  get '/help' => 'query#help', :format => 'bgps'
  #get '/help' => 'query#help', :format => 'html'
  get '/select_more_than_one' => 'query#help', :format => 'html'#, :anchor => 'faq'
  match '/results', to: 'query#help', :format => 'html', via: :get
  #map.query '/query.:format', :controller => "query", :action => "index"
  ##map.table '/table.:format', :controller => "table", :action => "write" , :format => 'html'
  #map.help '/help', :controller => "query", :action => "help", :format => 'html'
  #map.about '/about', :controller => "query", :action => "about", :format => 'html'
  #map.advanced_query_help "/help", :anchor => 'querying', :controller => "query", :action => "help", :format => 'html'
  #map.select_more_than_one "/help", :anchor => 'faq', :controller => "query", :action => "help", :format => 'html'
  #map.results "/help", :anchor => 'results', :controller => "query", :action => "help", :format => 'html'
end

app/controllers/query_controller.rb
class QueryController < ApplicationController
  #def iframe_action
  #  response.headers["X-FRAME-OPTIONS"] = "ALLOW-FROM http://www.w3schools.com/"
  #  render_something
  #end

  @per_page = 50
  @k ||= nil

  def download
    send_data @k, :filename => 'query.csv', :type => 'text/csv'
  end

  def index
    # condition hash
    cnd = {}
    # page to fetch
    current_page = params[:page].to_i > 0 ? params[:page].to_i : 1

    # q_value filter
    params[:filter] ||= "jtk_q_value"
    if params[:query]
      params[:filter] = params[:query][:filter]
    end
    #params[:filter]

    if ProbesetStat.pval_filters.flatten.include?(params[:filter])
      order = "#{params[:filter]} ASC"
    else
      order = "jtk_p_value ASC"
    end
    fv = params[:filter_value].to_f > 0.0 ? params[:filter_value].to_f : 0.05
    cnd[params[:filter].to_sym] = (0.0)..(fv)

    # tissue
    cnd[:assay_id] = params[:assays] if params[:assays]
    if params[:query_string].to_s.strip.empty?
      params[:query_string] = nil
    end

    # phase
    params[:phase_range] = "0-40" if params[:phase_range] == nil #? params[:phase_range] : "0-40"
    pv = params[:phase_range].split("-")
    pv_lower = pv[0].to_f
    pv_upper = pv[1].to_f
    cnd[:jtk_lag] = (pv_lower)..(pv_upper)

    # output mode
    params[:output_mode] ||= 'normal'
    @output_mode = params[:output_mode].to_sym

    # query match mode
    params[:match_mode] ||= 'gene_symbol'

    @match_mode = params[:match_mode].to_sym

    if params[:match_mode] == 'gene_symbol' && params[:query_string]
      @new_query = ""
      if params[:query_string]
        @match_mode = "extended".to_sym
        params[:query_string].split(" ").each do |word|
          @new_query += "@gene_symbol #{word} | "
        end
        params[:query_string] = @new_query[0..-3]
      end
    end

    if params[:match_mode] == 'unigene_id' && params[:query_string]
      @new_query = ""
      if params[:query_string]
        @match_mode = "extended".to_sym
        params[:query_string].split(" ").each do |word|
          @new_query += "@unigene_id #{word} | "
        end
        params[:query_string] = @new_query[0..-3]
      end
    end

    if params[:match_mode] == 'entrez_gene' && params[:query_string]
      @new_query = ""
      if params[:query_string]
        @match_mode = "extended".to_sym
        params[:query_string].split(" ").each do |word|
          @new_query += "@entrez_gene #{word} | "
        end
        params[:query_string] = @new_query[0..-3]
      end
    end

    if params[:query_string]
      #if match_mode
      @new_query = ""
      @match_mode = "extended".to_sym
      params[:query_string].split("\n").each do |word|
        @new_query += "#{word} |"
      end
      params[:query_string] = @new_query[0..-3]
      @probeset_stats = ProbesetStat.search(params[:query_string],
        :page => current_page, :per_page => @per_page, :with => cnd,
        :order => order, :match_mode => @match_mode,
        :include => [:probeset_data, :probeset, :probeset_stats])
    else
      @probeset_stats = ProbesetStat.search(:page => current_page,
        :per_page => @per_page, :with => cnd,
        :order => order,
        :include => [:probeset_data, :probeset, :probeset_stats])
    end


    if params[:number_entries].to_i > 0
      if params[:filter] =~ /^jtk/
        @k = "Probeset_ID,Symbol,Time,Values,JTKP,JTKQ,JTKperiod,JTKphase,Tissue\n"
      elsif params[:filter] =~ /^cosopt/
        @k = "Probeset_ID,Symbol,Time,Values,LombScargle_P,LombScargle_Q,LombScargle_period,LombScargle_phase,Tissue\n"
      end
      k = 1
      counter = params[:number_entries].to_i
      while counter > 0
        if counter >= 1000
          pp = 1000
        else
          pp = counter
        end
        #logger.info("Katharina #{k} and PP #{pp}")
        if params[:query_string]
          probeset_stats = ProbesetStat.search(params[:query_string],
          :page => k, :per_page => pp,
          :with => cnd,
          :order => order, :match_mode => @match_mode,
          :include => [:probeset_data, :probeset, :probeset_stats])
        else
          # max matches is evil!!!
          probeset_stats = ProbesetStat.search(:page => k,
            :per_page => pp, :with => cnd,
            :order => order, :max_matches => params[:number_entries].to_i,
            :include => [:probeset_data, :probeset, :probeset_stats])
        end
        #filename = "#{RAILS_ROOT}/test.nina.txt"
        #logger.debug "Person attributes hash: #{@person.attributes.inspect}"
        #logger.info "Filename: #{filename}"
        #logger.fatal "Terminating application, raised unrecoverable error!!!"
        #puts filename
        #if params[:query_string]
        #  xprobeset_stats = ProbesetStat.search(params[:query_string],
        #    :page => current_page, :per_page => params[:number_entries].to_i,
        #    :with => cnd,
        #    :order => order, :match_mode => @match_mode,
        #    :include => [:probeset_data, :probeset, :probeset_stats])
        #else
        #  xprobeset_stats = ProbesetStat.search(:page => current_page, :per_page => params[:number_entries].to_i,
        #    :with => cnd,
        #    :order => order,
        #    :include => [:probeset_data, :probeset, :probeset_stats])
        #end
        if params[:filter] =~ /^jtk/
          #logger.info("HURRRY #{params[:number_entries].to_i}")
          #logger.info("HURRRY length #{probeset_stats.length}")
          for i in 0...pp
            #logger.info("This is were DIE #{i}")
            probeset_stat = probeset_stats[i]
            break unless probeset_stat
            probeset = probeset_stats[i].probeset
            next unless probeset
            gene_symbol = probeset.gene_symbol
            id = probeset.probeset_name
            probeset_data = probeset_stat.probeset_data
            time_points = probeset_data.time_points.delete("\"[]").gsub(/,/,';')
            data_points = probeset_data.data_points.delete("\"[]").split(",")
            data_points = data_points.map { |e| (e.to_f*100).round/100.to_f}
            data_points = data_points.join(";")
            jtkp = probeset_stat.jtk_p_value
            jtkq = probeset_stat.jtk_q_value
            jtkperiod = probeset_stat.jtk_period_length
            jtkphase = probeset_stat.jtk_lag
            tissue = probeset_stat.assay_name
            @k += "#{id},#{gene_symbol},#{time_points},#{data_points},#{jtkp},#{jtkq},#{jtkperiod},#{jtkphase},#{tissue}\n"
          end
        elsif params[:filter] =~ /^cosopt/
          for i in 0...params[:number_entries].to_i
            probeset_stat = probeset_stats[i]
            break unless probeset_stat
            probeset = probeset_stats[i].probeset
            next unless probeset
            gene_symbol = probeset.gene_symbol
            id = probeset.probeset_name
            probeset_data = probeset_stat.probeset_data
            time_points = probeset_data.time_points.delete("\"[]").gsub(/,/,';')
            data_points = probeset_data.data_points.delete("\"[]").split(",")
            data_points = data_points.map { |e| (e.to_f*100).round/100.to_f}
            data_points = data_points.join(";")
            jtkp = probeset_stat.cosopt_p_value
            jtkq = probeset_stat.cosopt_q_value
            jtkperiod = probeset_stat.cosopt_period_length
            jtkphase = probeset_stat.cosopt_phase
            tissue = probeset_stat.assay_name
            @k += "#{id},#{gene_symbol},#{time_points},#{data_points},#{jtkp},#{jtkq},#{jtkperiod},#{jtkphase},#{tissue}\n"
          end
        end
        k = k + 1
        counter = counter - 1000


      end
      #File.delete(filename)
    else
      @k = nil
    end

    if params[:query_string] && params[:match_mode] == 'gene_symbol'
      fields = params[:query_string].split("@gene_symbol")
      params[:query_string] = fields[1..-1].join("\n").delete(" | ")
    end

    if params[:query_string] && params[:match_mode] != 'gene_symbol'
      fields = params[:query_string].split("|")
      params[:query_string] = fields.join("\n")
    end

    #download(k) if k


    # if you want to log messages, look at the Rails logger functionality
    # puts "@probeset_stats = #{@probeset_stats.length}"
    respond_to do |format|
      format.html {render_to_string}
      format.bgps do
        @unigene_id = params[:query_string]
        render :action => "index", :layout => '/layouts/bgps.html.haml'
      end
      #format.bgps {render :layout => '/layouts/bgps.html.haml',:action => "index"} #:action => "index",
      #end
      format.js { render_to_string  :json => @probeset_stats.to_json }
      format.xml { render_to_string  :xml => @probeset_stats.to_xml }
    end

    send_data @k, :filename => 'query.csv', :type => 'text/csv' if @k
  end


end

app/helpers/query_helper.rb
module QueryHelper
end

app/views/query/_form.html.haml
= form_for(:query,:html=>{:name=>"myForm",:onsubmit=>"return validateForm(this)",:onclick => "return validateForm(this)"}) do |f|
  .params.span-14.last
    .span-15.last
      = f.label :example, "Enter a search"
      %br
      %span.help
        (Examples
        = link_to("1451371_at 1422470_at gnf1m00037_a_at", query_path(:params => {:query_string => "1451371_at\n1422470_at\ngnf1m00037_a_at", :match_mode => "any"} ))
        or
        = link_to("Arntl", query_path(:params => {:query_string => "Arntl"} ))
        or
        = link_to("kinase inhibitor", query_path(:params => {:query_string =>  "kinase inhibitor", :match_mode => "extended"} ))
        )
      .qbox.span-5.last{:style => "padding-bottom: 1px;"}
        = text_area_tag :query_string, params[:query_string]
        /= f.text_area :query_string, :value => params[:query_string]

      .span-10.last
        %b Query syntax mode:
        - @match_mode = params[:match_mode]
        = radio_button_tag(:match_mode, "gene_symbol" ,(@match_mode == "gene_symbol" ? true : false))
        = f.label :match_mode_any, "by gene symbol"
        /= radio_button_tag(:match_mode, "any", (@match_mode == "any" ? true : false ))
        = radio_button_tag(:match_mode, "any", (@match_mode == "any" ? true : false))
        = f.label :match_mode_any, "simple"
        = radio_button_tag(:match_mode, "extended", (@match_mode == "extended" ? true : false ))
        = f.label(:match_mode_advanced, "advanced")
        = link_to(image_tag('questionmark_orange3.png', :alt=> "Query help page"), help_path())
        / For develop purposes
        /= params[:query_string]


      .span-10.last
        .span-10{:style => "padding-bottom: 10px;"}
          = f.label :filter, "Choose probability filter"
          = f.select :filter, options_for_select(ProbesetStat.pval_filters, :selected => params[:filter])#, params[:filter] || "cosopt_q_value"), :name => "filter"
          %br{:style => "padding-bottom: 10px;"}
          = f.label :filter_value, "Probabily cut-off value"
          = f.text_field :filter_value, :value => (params[:filter_value] || "0.05") ,:size => 5, :name => "filter_value"
          %span.help ("0.5" or "2e-10")
          %br{:style => "padding-bottom: 10px;"}
          = f.label :phase_range, "JTK phase range"
          = f.text_field :phase_range, :value => (params[:phase_range] || "0-40"), :size => 5, :name => "phase_range"
          %span.help ("0-6" or "10.30-11.10")

      .span-10.last
        %b Output mode
        - @output_mode = params[:output_mode]
        = radio_button_tag(:output_mode, "normal",(@output_mode == "normal" ? true : false))
        = f.label :output_mode_any, "normal"
        /= radio_button_tag(:output_mode, "any", (@output_mode == "any" ? true : false ))
        = radio_button_tag(:output_mode, "slim",(@output_mode == "slim" ? true : false))
        = f.label :output_mode_any, "slim"
        %br
        = f.label :number_entries, "Number of entries to download "
        = f.text_field :number_entries, :value => (params[:number_entries] || "0"),:size => 5, :name => "number_entries"
        %span.help ("50" or "100", max: "1000")
        /= radio_button_tag(:output_mode, "extended", (@output_mode == "extended" ? true : false ))
        /= label_tag(:output_mode_advanced, "advanced")
        /= link_to(image_tag('questionmark_orange3.png', :alt=> "Advanced query help page"), advanced_query_help_path(    ))

      .span-10.last
        .label
          = f.label :assays, "Select one or more experiments to view"
          = link_to(image_tag('questionmark_orange3.png', :alt=> "Experiment help page"), select_more_than_one_path(:anchor => 'faq'))
          %br
          %span.help (If nothing is selected, CIRCA will search all experiments.)
          = select_tag(:assays, options_for_select(Assay.all.collect {|e| [e.name ,  e.id.to_s] }, params[:assays]), {    :multiple => true,  :style => "height: 200px;"})
        .span-15.hov=f.submit "Search"

app/views/query/advanced_query_help.html.haml
%h2 Query Help
%p
  There are two mode of querying CircaDB:
  %a(href="#simple") Simple
  and
  %a(href="#advanced") Advanced.
%h3
  %a(name="simple") Simple Query Mode
%p
  This is the default. Simply enter a set of terms and the engine will query for
  each term seperately, then join all of the results from each separate term together
  into the final result. In other words a query for <code>kinase inhibitor</code>
  will return all entries with the word <code>kinase</code> together with any entry
  that has <code>inhibitor</code> in their respective annotations.
%p
  This is usually not what one would want returned from such a query. This is where
  the advanced query mode comes in.

%h3
  %a(name="advanced") Advanced Query Mode
%p
  Once the "advanced query mode" checkbox has been selected, the query strings
  are no longer simply split into individual queries. As the saying goes "with
  great power comes great responsibility". In a nutshell, you must now use the
  underlying Sphinx search engine's
  %a(href="http://sphinxsearch.com/docs/2.0.5/extended-syntax.html") extended syntax query mode.


%p
  Briefly, the default behavior of the query <code>kinase inhibitor</code> would bring
  back all entries that match both <code>kinase <b> AND </b> inhibitor</code>.
  Instead of an implicit <code>OR</code> between terms, there is now an implicit
  <code>AND</code> between terms.
%p
  To bring back the <code>OR</code> behavior you would need to separate terms
  with a <code>|</code> (a vertical bar, or "pipe") character. E.g.
  <code> kinase | inhibitor</code>.
%p
  To bring back the specific phrase "kinase inhibitor", you would need to
  surround both words with quotes. E.g. <code>"kinase inhibitor"</code>
%h3 More examples
%p
  %em Query for the exact phrase "kinase inhibitor" that also make mention of "mitochondrial"
  %br
  %code "kinase inhibitor" mitochondrial
%p
  %em Query for kinases, but not any entry with "inhibitor" in the record
  %br
  %code kinase !inhibitor

%h3 Even more examples
%p
  Sphinx is a large a powerful system. You can review all of the various
  ways to use the extended syntax at the
  %a(href="http://sphinxsearch.com/docs/2.0.4/extended-syntax.html") Sphinx extended query syntax help page

%h3 CircaDB Query Fields
%p
  Having read the above, you may be wondering what fields you can use to query CircaDB. The annotation is straight from the Affymetrix annotation files. We have pulled out certain columns from that file and indexed them as follows:

%table
  %tr
    %th Field
    %th Description
  %tr
    %td probeset_name
    %td The Affymetrix probeset name
  %tr
    %td transcript_id
    %td The transcript ID
    %td
  %tr
    %td representative_public_id
    %td
  %tr
    %td unigene_id
    %td Unigene ID
  %tr
    %td gene_symbol
    %td NCBI gene symbol
  %tr
    %td gene_title
    %td Full gene title
    %td
  %tr
    %td entrez_gene
    %td The Entrez gene ID
  %tr
    %td swissprot
    %td The SwisProt accession
  %tr
    %td refseq_protein_id
    %td The RefSeq protein accession
  %tr
    %td refseq_transcript_id
    %td The RefSeq NA sequence accession
  %tr
    %td target_description
    %td The description from the Affymetrix annotation file

app/views/query/help.html.haml
.span-3.last{:style => " padding: 5px;" }
  %table
    %tr
      %th
        %a(href="#querying") Queriyng
    %tr
      %th
        %a(href="#simple") - Simple Search
    %tr
      %th
        %a(href="#advanced") - Advanced Search
    %tr
      %th
        %a(href="#probability") - Probability
    %tr
      %th
        %a(href="#phase_range") - Phase range
    %tr
      %th
        %a(href="#results") Results
    %tr
      %th
        %a(href="#plot") - Plots
    %tr
      %th
        %a(href="#p-value") - p-Value
    %tr
      %th
        %a(href="#q-value") - q-Value
    %tr
      %th
        %a(href="#period") - Period
    %tr
      %th
        %a(href="#phase") - Phase
    %tr
      %th
        %a(href="#faq") FAQ

.span-14.last{:style => "border-left: 2px double #E5ECF9; padding: 13px;" }
  %h1
    CIRCA Help
  %p
    Welcome to the CIRCA help page. Here you will find all the information
    you need for a successful search.
  %h2
    %a(name="querying"){:style => "color:#111;"} Querying CircaDB
  %p
    There are three modes of querying CircaDB:
    By gene symbol,
    %a(href="#simple") Simple
    and
    %a(href="#advanced") Advanced.
    In all three modes using the wildcard character "*" is possible.
  %h3
    %a(name="simple"){:style => "color:#111;"} Simple Query Mode
  %p
    This is the default. Simply enter a set of terms and the engine will query for
    each term separately, then join all of the results from each separate term together
    into the final result. In other words a query for <code>kinase inhibitor</code>
    will return all entries with the word <code>kinase</code> together with any entry
    that has <code>inhibitor</code> in their respective annotations.
  %p
    This is usually not what one would want returned from such a query. This is where
    the advanced query mode comes in.

  %h3
    %a(name="advanced"){:style => "color:#111;"} Advanced Query Mode
  %p
    Once the "advanced query mode" check-box has been selected, the query strings
    are no longer simply split into individual queries. As the saying goes "with
    great power comes great responsibility". In a nutshell, you must now use the
    underlying Sphinx search engine's
    %a(href="http://sphinxsearch.com/docs/2.0.5/extended-syntax.html") extended syntax query mode.


  %p
    Briefly, the default behavior of the query <code>kinase inhibitor</code> would bring
    back all entries that match both <code>kinase <b> AND </b> inhibitor</code>.
    Instead of an implicit <code>OR</code> between terms, there is now an implicit
    <code>AND</code> between terms.
  %p
    To bring back the <code>OR</code> behavior you would need to separate terms
    with a <code>|</code> (a vertical bar, or "pipe") character. E.g.
    <code> kinase | inhibitor</code>.
  %p
    To bring back the specific phrase "kinase inhibitor", you would need to
    surround both words with quotes. E.g. <code>"kinase inhibitor"</code>
  %h4 More examples
  %p
    %em Query for the exact phrase "kinase inhibitor" that also make mention of "mitochondrial"
    %br
    %code "kinase inhibitor" mitochondrial
  %p
    %em Query for kinases, but not any entry with "inhibitor" in the record
    %br
    %code kinase !inhibitor

  %h4 Even more examples
  %p
    Sphinx is a large a powerful system. You can review all of the various
    ways to use the extended syntax at the
    %a(href="http://sphinxsearch.com/docs/2.0.4/extended-syntax.html") Sphinx extended query syntax help page

  %h4 CircaDB Query Fields
  %p
    Having read the above, you may be wondering what fields you can use to query CircaDB. The annotation is straight from the Affymetrix annotation files. We have pulled out certain columns from that file and indexed them as follows:

  %table
    %tr
      %th Field
      %th Description
    %tr
      %td probeset_name
      %td The Affymetrix probeset name
    %tr
      %td transcript_id
      %td The transcript ID
    %tr
      %td representative_public_id
      %td
    %tr
      %td unigene_id
      %td Unigene ID
    %tr
      %td gene_symbol
      %td NCBI gene symbol
    %tr
      %td gene_title
      %td Full gene title
    %tr
      %td entrez_gene
      %td The Entrez gene ID
    %tr
      %td swissprot
      %td The SwisProt accession
    %tr
      %td refseq_protein_id
      %td The RefSeq protein accession
    %tr
      %td refseq_transcript_id
      %td The RefSeq NA sequence accession
    %tr
      %td target_description
      %td The description from the Affymetrix annotation file
  %h3
    %a(name="probability"){:style => "color:#111;"} Probability filter
  %p
    The probability filter can be used to narrow the output to the most significant results. The database can be filtered for
    %a(href="#p-value") p-values
    and
    %a(href="#p-value") q-values
    produced by the different algorithms. The given value is used as the upper cutoff.
  %h3
    %a(name="phase_range"){:style => "color:#111;"} Phase range
  %p
    The here specified range can be used to filter for genes that share the same
    %a(href="#range") phase.
    Only the phases computed by JTK are considered during this filter step.
  %h2
    %a(name="results"){:style => "color:#111;"} Understanding the results
  %p
    There are three different algorithms to statistically test if a dataset
    is cyclic or not. More information about these algorithms can be found
    in the #{link_to("About", about_path())} tab.
  %p
    %b Note:
    %i For all the algorithms we tested cyclic behavior for a range of different periods, except for the DeLichtenberg were we only looked for a period of 24 hours.
  %h3
    %a(name="plot"){:style => "color:#111;"} Plots
  %p
    As result we will see a plot, where the X-axis is the time in
    hours and the Y-axis reflects the expression levels measured
    on the individual gene chips. The background shaded areas represent the cycle of light and dark conditions based on CT times.
  =image_tag("plot.png", :alt=> "PLOT")
  %h3
    %a(name="p-value"){:style => "color:#111;"} p-Value
  %p
    This statistical size, is the estimated probability of rejecting the null hypothesis. Here the null hypothesis is a dataset not being cyclic. The lower the p-value the more significant is the test result.
  %h3
    %a(name="q-value"){:style => "color:#111;"} q-Value
  %p
    The q-value of a test is the minimum false discovery rate at which a gene is mistakenly called cyclic.
  %h3
    %a(name="period"){:style => "color:#111;"} Period
  %p
    This value gives information on how often the cycle is repeated. Is the period
    %i 24
    , the pattern reoccurs every 24 hours.
  %h3
    %a(name="phase"){:style => "color:#111;"} Phase
  %p
    The phase reflects the timing in the individual tissues. The DeLichtenberg algorithm does not provide this value in its output.
  %h2
    %a(name="faq"){:style => "color:#111;"} Frequently asked questions
  %table
    %tr
      %th How do I select more than one experiment?
      %td "Ctrl+Right Click" lets you select multiple experiments ("Command+Right Click" for mac users)
    %tr
      %th How do I request a data set be added to CircaDB?
      %td
        Researchers can request that a particular data set be added by submitting an issue at our project page hosted at
        %a(href="https://github.com/itmat/circadb/issues") Github.

.span-20.last.push-6{:style => "text-align:center; padding: 13px;" }
  %p
    %a(href="#top") back to the top